<?php

namespace Inbenta\TwilioConnector\ExternalAPI;

use Inbenta\TwilioConnector\Helpers\Helper;


class TwilioAPIClient
{
    public $from;
    public $to;
    protected $transferFunctionUrl;

    function __construct(string $transferFunctionUrl = '')
    {
        $this->transferFunctionUrl = $transferFunctionUrl;
    }

    /**
     * Build an external session Id using the following pattern:
     * 
     * @return String|null
     */
    public static function buildExternalIdFromRequest()
    {
        parse_str(file_get_contents('php://input'), $request);

        if (isset($request['AccountSid']) && isset($request['DialogueSid'])) {
            $response = 'twilio-' . $request['DialogueSid'];

            return $response;
        }
        return null;
    }


    /**
     * Establishes the Twilio sender (user) directly with the provided phone numbers
     * @param String $companyPhoneNumber
     * @param String $userPhoneNumber
     * @return void
     */
    public function setSenderFromId($companyPhoneNumber, $userPhoneNumber)
    {
        $this->from = '+' . $companyPhoneNumber;
        $this->to = '+' . $userPhoneNumber;
    }

    /**
     *   Generates the external id used by HyperChat to identify one user as external.
     *   This external id will be used by HyperChat adapter to instance this client class from the external id
     *   @return String external Id
     */
    public function getExternalId()
    {
        $response = str_replace(':+', '', 'twilio-' . $this->from . '-' . $this->to);
        $response = str_replace('+', '', $response);
        return $response;
    }

    /**
     *  Retrieves the Account SID from the external ID generated by the getExternalId method
     *  @param String $externalId
     *  @return String|null user phone number or null
     */
    public static function getUserNumberFromExternalId($externalId)
    {
        $externalIdExploded = explode('-', $externalId);
        if (array_shift($externalIdExploded) == 'twilio') {
            return $externalIdExploded[1];
        }
        return null;
    }

    /**
     *  Retrieves the company phone number from the external ID generated by the getExternalId method
     *  @param String $externalId
     *  @return String|null Company phone number or null
     */
    public static function getCompanyNumberFromExternalId($externalId)
    {
        $externalIdExploded = explode('-', $externalId);
        if (array_shift($externalIdExploded) == 'twilio') {
            return $externalIdExploded[0];
        }
        return null;
    }

    /**
     * Sends a message to Twilio. Needs a message formatted with the Twilio notation
     *
     * @param string $message
     * @param bool $print
     * @param bool $isEscalation
     * @return array
     */
    public function sendMessage(string $message, bool $print = false, bool $isEscalation = false)
    {
        $message = Helper::removeInitialDots($message);
        if ($isEscalation && $this->transferFunctionUrl !== '') {
            $response = [
                "actions" => [
                    [
                        "say" => $message
                    ],
                    [
                        "handoff" => [
                            "channel" => "voice",
                            "uri" => $this->transferFunctionUrl,
                            "method" => "POST"
                        ]
                    ]
                ]
            ];
        } else {
            $response = [
                "actions" => [
                    [
                        "say" => $message
                    ],
                    [
                        "listen" => true
                    ]
                ]
            ];
        }

        if (!$print) {
            return $response;
        }

        header('Content-Type: application/json');
        echo json_encode($response, JSON_UNESCAPED_SLASHES);
        die;
    }

    /**
     *   Method needed
     */
    public function showBotTyping($show = true)
    {
        return true;
    }

    /**
     * Sends a message to Twilio. Needs a message formatted with the Twilio notation
     * @param string $text
     * @param bool $isEscalation = false
     */
    public function sendTextMessage(string $text, bool $isEscalation = false)
    {
        $message = $text;
        if (strpos($text, "<") !== false) { //If text has a type of html tags
            $text = Helper::handleMessageWithLinks($text);
        }
        $message = Helper::cleanMessage($text);
        $printResponse = $isEscalation;
        $this->sendMessage($message, $printResponse, $isEscalation);
    }
}
